### ISSUE TITLE
On click anywhere gives an parse error(Error: Syntax error)

### ISSUE THREAD

**Issue by manmohanagarwal4** [VadimDez/ngx-filter-pipe#60] opened 2018-04-04 09:35 UTC
I have added the filter module. It is working fine . But giving a console error when click on anywhere on filter item shows in html view.

 I am sharing the full console error please look into it.

Uncaught Error: Syntax error, unrecognized expression: #
    at Function.Sizzle.error (scripts.bundle.js:1541)
    at Sizzle.tokenize (scripts.bundle.js:2193)
    at Sizzle.select (scripts.bundle.js:2620)
    at Function.Sizzle [as find] (scripts.bundle.js:845)
    at jQuery.fn.init.find (scripts.bundle.js:2873)
    at new jQuery.fn.init (scripts.bundle.js:2983)
    at jQuery (scripts.bundle.js:139)
    at Function.e._getParentFromElement (scripts.bundle.js:13788)
    at HTMLDocument.e._clearMenus (scripts.bundle.js:13788)
    at HTMLDocument.dispatch (scripts.bundle.js:5183)

**Comment by VadimDez** [comment] 2018-04-04 09:40
Could you please share the code? It's kind of hard to understand what is causing the error from the log  since all i can see are jQuery and Sizzle methods

**Comment by manmohanagarwal4** [comment] 2018-04-04 09:50
Sorry It is my mistake. Other code lib give me that error. I am new on git-hub So I do not know many things here.

**Comment by VadimDez** [comment] 2018-04-04 09:51
Closing since not the error caused by `ngx-filter-pipe`

**Closed by VadimDez** 2018-04-04 09:51 UTC
